### PR TITLE
simple http example for Spark.publish()

### PR DESCRIPTION
**Pull request by kennethlimcp**
Gives the user an idea on how to see it in action if it's their first encounter with SSE

### CODE REVIEW

**Comment by zsup** [comment]
hmm. does this actually work? not for me; it holds open the socket but I don't get data

**Comment by kennethlimcp** [comment]
It works on chrome for me. Maybe notnfor other browsers? :)

**Comment by towynlin** [comment]
I find that I have to:
1. Go to the URL
2. View source
3. Close the original non-source window

Not a great user experience. I'm going to close this Kenneth, because posting this will, I think, generate more confusion than clarity.

Thank you anyway—great impulse! If only the browsers would show the event stream as text! :smile_cat:

**Comment by kennethlimcp** [comment]
@towynlin I used it on my chrome without going to the `view source` and it shows:

> :ok
> 
> event: geo
> data: {"data":"latitude: -100.175450 longitude: 25.342350","ttl":"60","published_at":"2014-03-17T23:29:29.055Z","coreid":"48ff6c065067555048241387"}
> 
> event: timkay/q
> data: {"data":"q 3 x 00e35d44aa096aa1 (56 bits)\n","ttl":"60","published_at":"2014-03-17T23:29:29.620Z","coreid":"53ff70065067544841350587"}
> 
> event: timkay/z
> data: {"data":"1 x 6100c6c3\n","ttl":"60","published_at":"2014-03-17T23:29:30.450Z","coreid":"53ff70065067544841350587"}
> 
> event: geo
> data: {"data":"latitude: -100.175450 longitude: 25.342350","ttl":"60","published_at":"2014-03-17T23:29:31.060Z","coreid":"48ff6c065067555048241387"}
> 
> event: timkay/z
> data: {"data":"2 x 7100c6c3\n","ttl":"60","published_at":"2014-03-17T23:29:31.211Z","coreid":"53ff70065067544841350587"}
> 
> event: Uptime
> data: {"data":"2:29:13","ttl":"60","published_at":"2014-03-17T23:29:31.393Z","coreid":"50ff69065067545649550287"}

But we already have Tutorials by Bko on how to get started. They need to work with html files though to get started :)

**Pull request closed without merging**
