### PR TITLE
Update hardware.md

### PR DESCRIPTION
**Pull request by cesschneider**
Updated broken documentation links

### CODE REVIEW

**Comment by technobly** [comment]
Hi cesschneider! Pretty sure these links should still be relative instead of absolute. Curious if you tried them that way first?

**Comment by cesschneider** [comment]
You are right! Actually I've copied the right URL from address bar and pasted on documentation. I've just created a new commit with fixed URLs.

**Comment by kennethlimcp** [comment]
@cesschneider, seems like the relative links are still incorrect. 

Example. `pinMode` is `firmware/#setup-pinmode`

**Comment by kennethlimcp** [comment]
@cesschneider, thanks!

**Pull request merged**
