### PR TITLE
Added A0 wake-up info

### PR DESCRIPTION
**Pull request by ScruffR**
Added A0 wake-up info for `Spark.sleep(SLEEP_MODE_DEEP, sec)`

### CODE REVIEW

**Comment by ScruffR** [comment]
Aparently to have this work as stated in the STM32 docs some additional setup has to be done in `Spark.sleep(SLEEP_MODE_DEEP)` see 
http://community.spark.io/t/how-to-put-spark-core-to-sleep-and-wakeup-on-interrupt-signal-on-a-pin/5947/56

**Comment by kennethlimcp** [comment]
@ScruffR can you give more information about this for me to decide to pull this in or close?

**Comment by ScruffR** [comment]
I'm not sure if things have changed since this post of @satishgn 
http://community.spark.io/t/how-to-put-spark-core-to-sleep-and-wakeup-on-interrupt-signal-on-a-pin/5947/61

But if things are still the same, my PR might have been a bit premature ;-)

Best to read the posts 55ff or ask Satish if this should be closed (if things are still the same) or pull (if it fits).

**Comment by jme783** [comment]
@ScruffR  closing this as we've moved our documentation here: https://github.com/spark/docs. Please re-open this P/R in the new repo. Thanks!

**Pull request closed without merging**
