### PR TITLE
Update examples.md

### PR DESCRIPTION
**Pull request by hseghetti**
In the second image the connection is not correct. Please notice that the positive pin is connected on the GND output.

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@hseghetti how do you tell that it is incorrect? Looking at http://cdn.instructables.com/FPB/EG4N/FK8FVU92/FPBEG4NFK8FVU92.LARGE.jpg, the connections seems to be correct.

Also, i would prefer to fix the image than to add a note to correct something that is wrong :)

**Comment by hseghetti** [comment]
The description is: The negative (shorter) pin of the LED is connected to ground via a resistor and the positive (longer) pin is connected to D0.
And in the second image, the negative pin is connected to D0 via a resistor and the positive is conneted to the GND.

I agree with you @kennethlimcp about fix the image. Fix the image is the best solution, but I am not a good UI to change it =)

**Comment by bkobkobko** [comment]
OK, I looked at this and it is the Fritzing diagram that is inconsistent with the text and the other picture.  Everything else seems to  be correct.

The two diagrams are just in conflict about where the resistor should go (it doesn't matter but it would be best to be consistent).

I am not sure why you think the negative pin is connected to D0, it looks to me like the longer lead (always the anode or plus side) is connected to D0 via the resistor.

**Comment by hseghetti** [comment]
@bkobkobko  You are right. The pins are correct. Just was a confusion with the differences between the diagrams. I will decline this pull request. 
Thank you for yours comments

**Pull request closed without merging**
