### PR TITLE
Fixed errors and added missing function

### PR DESCRIPTION
**Pull request by gregersrygg**
There is no function getDevices, it's listDevices. The first argument in the callback seems to be `err`, and not `devices`.
Also found the method I _actually_ wanted in the source code, `getDevice` by it's id. So I added a short doc for it as well.

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@solojavier can you verify this?

**Comment by solojavier** [comment]
yes, it seems correct :+1:

**Comment by kennethlimcp** [comment]
@gregersrygg and @solojavier thanks!

**Comment by gregersrygg** [comment]
@kennethlimcp np :smile:

**Pull request merged**
