### PR TITLE
Clarification for Vin pin

### PR DESCRIPTION
**Pull request by ScruffR**
There have been some discussions on the forum about the meaning/use of the Vin pin.
Most recent 
http://community.spark.io/t/does-spark-core-supplies-5v/7066
http://community.spark.io/t/gps-to-spark-core/7058

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@ScruffR, we also need to inform the user that there's a limit to how much current they can draw through that pin since there a protection diode between the USB +5V and Vin.

**Comment by ScruffR** [comment]
@kennethlimcp, have you got any info about the rating of this diode? 
In that case the diode will reduce the Vin voltage to less than the typical 5V (5V minus forward voltage drop of the diode). This should be documented, too.
I wanted to check the Eagle files, but thought the general update was more important than these details, so I pushed it out ASAP.
And since there is a diode, the limitation not to power concurrently via USB and Vin might not apply after all. How do you and the team see this?

**Comment by bkobkobko** [comment]
> And since there is a diode, the limitation not to power concurrently via USB and Vin might not apply after all. How do you and the team see this?

The diode prevents reverse current back into the USB power supply.  If you want to use both USB and VIN and protect both from reverse current, you would need an external diode on the VIN secondary power to the core. So it could work but it is not as easy as just hooking it up.

The diode in the BOM is a Schottky barrier diode with 0.4 to 0.45 V Vf at 1A.  At lower currents, the Vf is lower too, about 0.1 to 0.2 V at 200-400mA.

http://www.vishay.com/docs/88935/ss1p3.pdf

**Comment by ScruffR** [comment]
Thanks Brian, that's most valuable input. 
This would fit nicely into the "Hardware Datasheets" section of the docs , near the 3.3V regulator  ;-)

And sure, it'd need an external diode to protect the outside cicuitry, but if the on-board one wasn't there we'd be a bit stuck and the docs would have to stress the demand that USB and Vin **must not** be powered concurrently - fortunately precautions have been taken.

**Pull request merged**
