### PR TITLE
ZH for connect.md and troubleshooting.md

### PR DESCRIPTION
**Pull request by kennethlimcp**
The `known issues` under troubleshooting.md is left untranslated since it's changing rapidly.

### CODE REVIEW

**Comment by joegoggins** [comment]
Hi @kennethlimcp , thanks for translating all of this, awesome!
It appears that you accidentally removed the doc/connect.md doc in this pull request. Once you restore this file, this pull request should merge cleanly (and I'll go ahead and yank it into the master repo).

**Comment by kennethlimcp** [comment]
Alright let me get it sorted. A new github user always figuring out how to be in sync with the forked repo :)

**Comment by kennethlimcp** [comment]
@joegoggins seems like i got it sorted :)

**Comment by joegoggins** [comment]
Yes indeed you did sir @kennethlimcp , merged, thank you!

**Pull request merged**
