### PR TITLE
Initial Javascript docs

### PR DESCRIPTION
**Pull request by solojavier**

### CODE REVIEW

**Comment by edgarsilva** [comment]
@solojavier Looks good to me, but I think we need @towynlin and @zsup to greenlit this changes before we merge.

**Comment by towynlin** [comment]
Thanks! In general looks good, but I see some spelling, capitalization, and grammar things to fix. I hope to get to it soon.

**Comment by zsup** [comment]
The content here is pretty good (although clearly very lacking in the device calls, which I think are _extremely_ important and need to be documented much more thoroughly). However, I think the organization needs a lot of work. The documentation should be done semantically, and organized by "the type of thing that somebody might want to do" rather than organized the way the code is organized. Think about the way that a user would come at it; they are trying to solve a problem, not research the code.

Here is a proposal for how the docs could be reorganized:
- Getting started
  - Installing/requiring the library
    - In node.js
    - On the client side (bower or downloaded)
  - Logging in
    - with username/password
    - with access token
  - Responses
    - using promises
    - using callbacks
    - using event listeners
- Device management
  - list devices
  - claim a device
  - remove a device
- device object
  - example object
  - commands
    - call
    - getVariable
    - all the rest
- Subscribing to events
- Working with code
  - Compiling code
  - Flashing code
  - Downloading a binary
- User management
  - Create a user
  - Login
  - Removing a token
- Development
  - Installing dependencies
  - Running tests
  - Running linter
  - Test coverage

Does that make sense?

@towynlin I would wait on reorganization before doing line edits, that should be the last step.

**Comment by towynlin** [comment]
Totally. I glanced at the first paragraph or two, made that comment, and moved on. Thanks!

**Comment by solojavier** [comment]
@zsup thanks for the feedback, we will work on the new organization and improvements

**Comment by solojavier** [comment]
I've updated the docs with new organization....

**Pull request merged**
