### PR TITLE
Update describing Network.macAddress

### PR DESCRIPTION
**Pull request by vk2tds**
The code for using the Mac Address is non-obvious. This example is taken from https://community.spark.io/t/how-to-get-mac-address/1411/5

### CODE REVIEW

**Comment by vk2tds** [comment]
Here is an update for the Network.macAddress() function

**Comment by kennethlimcp** [comment]
@vk2tds, Thanks for the PR!

I'm looking at making the code simpler without so many Serial.print.

Maybe something like this?

https://community.spark.io/t/is-there-a-network-ip-print-function/5102/8

Thanks!

**UPDATE**

@vk2tds, i guess you got the simplest example possible. I tried to make it simpler but the BYTE to HEX string conversion isn't possible with `sprintf`.

If you change line 298 from `delay(1000);` to `while(!Serial.available()) SPARK_WLAN_Loop(); //hit Enter to continue!`, we are good to go with this PR.  ;)

**Comment by technobly** [comment]
I'll make the extra change in a second here:

`while(!Serial.available()) SPARK_WLAN_Loop(); // Hit any key to continue!`

**Comment by technobly** [comment]
Updated here:
https://github.com/spark/docs/commit/29e39b830cbfd070a3b5151f817b58aa828cb6e0

**Pull request merged**
