### PR TITLE
Update firmware.md

### PR DESCRIPTION
**Pull request by shawnjordan**
Converted old instances of Network object to WiFi

### CODE REVIEW

**Comment by bkobkobko** [comment]
Hi @shawnjordan 

Maybe you could fix the UPD --> UDP typo too?

**Comment by shawnjordan** [comment]
Done

**Comment by kennethlimcp** [comment]
@shawnjordan thanks!

**Comment by bkobkobko** [comment]
Thanks for the merge @kennethlimcp -- you beat me to it!

**Pull request merged**
