### PR TITLE
Update hardware.md

### PR DESCRIPTION
**Pull request by AlanGitMan**
Proposed additions to the Serial section. Also temp removed a broken link... made into a comment.

### CODE REVIEW

**Comment by technobly** [comment]
Thank you for the PR. I think at this time we should keep the hardware section clean and to the point. Extra details about the serial ports and implementation should go in the Firmware section, which it seems the link to is broken?

**Comment by technobly** [comment]
There is also the second TTL level serial port on D0, D1 that we must document as well, for a total of three serial ports.

**Comment by AlanGitMan** [comment]
Hiya, 

I agree that this article should be as simple and basic as possible, because it is where noobs will usually begin from. 

BUT, as a spark noob myself I was confused for a while because this "Arduino IDE compatible device" doesn't map "Serial.println" to the hardware port like Arduino does. I had got to the point where I was thinking maybe I had a faulty board!  So, I think there is value to pointing out upfront that Serial1 is how you access the TX and RX pins on spark - what do you think?

Yes, the "Serial functions" link at http://docs.spark.io/hardware/ is broken. 

As a general comment, I have found that the introductory material is good, except in those areas covering comms - one example, the explanatory programs for setting up a IP client could do with a lot more explanatory comments - and possibly an accompanying diagram. I am still very confused about which is the client and server. 

Also I think the recent long discussion about how to make the spark a truly stand alone board that continues working, even it it loses cloud connection, should be summarised in a simple way for the introductory pages.  I believe that a very large percentage of buyers will be looking for a single board computer with WIFI for stand alone LAN-based applications and don't want reliance on cloud connectivity (as many replies to that forum topic confirm).  Now that there IS a way to make spark work W-LAN only, making it look like spark can ONLY work when connected to the cloud would be a shame - and bad for business. 

What's the best place to raise these issues with the team?

Many thanks!

Best regards
Alan Trevennor.
Author "Practical AVR Microcontrollers" (2013)

**Comment by zsup** [comment]
Hey Alan, thanks for the feedback! Consider the issue raised. We'll definitely take your thoughts in mind the next time we go through and refactor the documentation, which should get a major refresh over the next couple of months as we prep our new hardware. However the best place to raise these issues (to make sure they stay on our to-do list) is to create one Github Issue for each thing you would like to see improved documentation for. Please be extremely specific so that your feedback is actionable. And if you are interested in taking a stab at some of the changes, and issuing a pull request, we'd gladly review them; as you saw from @technobly's feedback we will of course present our own perspective, but if you are up for going back and forth with us to reach a good solution, we appreciate the help :-)

**Comment by technobly** [comment]
@AlanGitMan I just checked the link and it worked for me:
http://docs.spark.io/firmware/#communication-serial

What browser / device are you using to open this link?  If you still see it not working can you see if there are any errors in the Console of your browser.  Right click and select Inspect Element, navigate to the Console and refresh the page.

It seems we have the second serial port documented now in the Firmware section which is great.  Just need to update this Hardware section as well now.

Also, `Serial.println()` does map to the Serial terminal on the computer much in the same way Arduino does.  It just so happens that the TX / RX pins of the Spark Core are an additional hardware serial port, unlike Arduino which is one and the same.  In addition to those two serial ports, the Spark Core has one more additional hardware serial port on D0, D1.  I know you know this by now, just stating it this way to show the similarities and differences between Spark Core and Arduino.

I'll take a stab at a quick edit of the hardware section that defines the 3rd serial port and briefly makes mention of which port goes to which hardware.  The image needs to be updated as well.

**Comment by zsup** [comment]
Oops that's my bad, I fixed the link and forgot to say anything here :-)

**Comment by technobly** [comment]
I just updated the [hardware page text](https://github.com/spark/docs/commit/cdd32003d7ef0db1aff2e0c2658869b893b94b68) and [image](https://github.com/spark/docs/commit/97acb5d34e94c245edefa8460203b517907d6b4a), I think that should wrap this up.  Please create a new issue for any further issues :)

**Comment by AlanGitMan** [comment]
Hi Zach, yes, I'd be very hppy to help with the documentation effort in
whatever ways I can.  Obviously, at my current level, I can't do anything
that requires very in-depth product knowledge, but I'd be happy to have a
shot at anything you guys care to point me at.

Best regards

Alan T

**Comment by AlanGitMan** [comment]
Hey guys,

That all looks great now - many thanks. This noob (and noobs who have yet to
visit!) thanks you for these clarifications :-)

Best regards

Alan Trevennor. 

Cornwall

UK

**Comment by zsup** [comment]
Thanks Alan for the help!

**Pull request closed without merging**
