### PR TITLE
Added Appendix: Firmware Upgrade using Serial Y-Modem protocol

### PR DESCRIPTION
**Pull request by satishgn**
core-firmware PR is over here: https://github.com/spark/core-firmware/pull/250

### CODE REVIEW

**Comment by m-mcgowan** [comment]
I feel that this should be a library, like Serial2 to avoid having users that don't use the feature still pay for the overhead in flash.

**Comment by satishgn** [comment]
Fine. I have created a trello card for this issue and will be working on this soon.

**Comment by m-mcgowan** [comment]
Thank you - I know our users will also think you for it!

**Comment by jme783** [comment]
@satishgn closing this as we've moved our documentation here: https://github.com/spark/docs. Please re-open this P/R in the new repo if it's still relevant. Thanks!

**Pull request closed without merging**
