### PR TITLE
explicit directions for flashing tinker from app

### PR DESCRIPTION
**Pull request by gitdoc67**

### CODE REVIEW

**Comment by technobly** [comment]
Ah yes, I remember this problem... you just keep going in circles if you don't click that little arrow.  Is this the same way on iOS (AND) Android Tinker Apps?  If not we might have to document the nuances between the two.

**Comment by gitdoc67** [comment]
I don't have Android devices to test so I cannot verify. This is iOS directions.

**Comment by technobly** [comment]
Hopefully someone with Android can chime in here and explain the difference... then we can make specific instructions per OS... e.g., 

**To reflash Tinker from within the app:**
- **iOS Users:**  Click the list button at the top left, then click the arrow next to your spark core. It will reveal the "Re-Flash Tinker" button.
- **Android Users:** blah blah blah.

**Comment by zsup** [comment]
In Android, when you've got a Core selected you hit the options button in the upper right, and get a drop down menu that includes "Reflash Tinker". See this screenshot: https://www.dropbox.com/s/nmk2udjmzxzhi8a/2014-07-07%2017.21.55.png

**Comment by technobly** [comment]
Thanks @zs- !

@docwisdom would you please update your PR to the following so that I may merge it?

---

The Tinker firmware is the default application program stored in the Spark Core upon its commissioning from the factory assembly line. You can always get back to it by putting the Core in the [factory reset mode](#buttons), or by re-flashing your Core with Tinker in the Spark mobile app. 

To reflash Tinker from within the app:
- iOS Users: Tap the list button at the top left. Then tap the arrow next to your desired Core and tap the "Re-flash Tinker" button in the pop out menu.
- Android Users: With your desired Core selected, tap the options button in the upper right and tap the  "Reflash Tinker" option in the drop down menu.

---

Copy/Pasteable:

<pre>
The Tinker firmware is the default application program stored in the Spark Core upon its     commissioning from the factory assembly line. You can always get back to it by putting the Core in the [factory reset mode](#buttons), or by re-flashing your Core with Tinker in the Spark mobile app. 
To reflash Tinker from within the app:
* iOS Users: Tap the list button at the top left. Then tap the arrow next to your desired Core and tap the "Re-flash Tinker" button in the pop out menu.
* Android Users: With your desired Core selected, tap the options button in the upper right and tap the  "Reflash Tinker" option in the drop down menu.
</pre>

**Comment by technobly** [comment]
@kennethlimcp I'm guessing you're going to add the extended version then?  Just checkin'

**Comment by kennethlimcp** [comment]
Did I miss it? I compared (visually) and thought it was available :p

**Comment by technobly** [comment]
Oh I missed his second commit down below... I figured it would show up top.  Thanks @kennethlimcp 

I'm currently fixing up the Listening Mode docs...

**Pull request merged**
