### PR TITLE
Made clearer which button is the reset button and which one the mode

### PR DESCRIPTION
**Pull request by mozzbozz**
It cost me some time that I didn't notice that I could hold the core the other way round and then the buttons where in a different direction ;)

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@mozzbozz, thanks! you can sign this: https://docs.google.com/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform before i pull it in? :)

**Comment by mozzbozz** [comment]
Well, I accept the CLA, however, I'm wondering why I need to provide such information (Telephone Number (sorry, but I won't provide this), Mailing Address (maybe if not public)? oO)... Also: Is the entered data only visible to Spark or also to the public?

**Comment by kennethlimcp** [comment]
This is maintained by spark and collected by them based on the Google Individual Contributor License Agreement, v1.1.

If you are not comfortable with it, I can open up a separate PR using my account :)

**Comment by mozzbozz** [comment]
Ok, I've signed the CLA ;)

**Comment by technobly** [comment]
@zs- Is the CLA required for all contributions or just firmware submissions?

**Comment by zsup** [comment]
not required for docs additions. Thanks @mozzbozz for signing it anyway, perhaps this will lead to pull requests to the firmware libraries or other open source repositories down the road :-)

**Pull request merged**
