### PR TITLE
Updated information on Spark.variable limitations

### PR DESCRIPTION
**Pull request by vk2tds**
Updated information on Spark.variable limitations

### CODE REVIEW

**Comment by kennethlimcp** [comment]
I'm suggesting the following as we can probably perform a merge for this PR:

`Currently, a user is allowed to define up to 10 Spark variables and each variable name is limited to a max of 12 characters.`

Thanks!

**Comment by vk2tds** [comment]
I am happy with this wording. Looks good

**Comment by kennethlimcp** [comment]
Could you edit your PR and i will pull it in? :+1:

**Comment by vk2tds** [comment]
I think I have done that. I am fairly new to Git

**Comment by kennethlimcp** [comment]
You did it just right for a beginner. Thanks! 

If you noticed, i'm also rather new :)

**Pull request merged**
